server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #數據源操作類型
    driver-class-name: com.mysql.cj.jdbc.Driver # 驅動包
    url: jdbc:mysql://localhost:3306/springcloudlearn?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: mm12583

mybatis:
 mapper-locations: classpath:mapper/*.xml #resource下路徑
# type-aliases-package: com.frank.springcloud.payment8001.entities #所有Entity所在package 已刪除改為共用地
 type-aliases-package: com.frank.springcloud.commonsapi.entities #所有Entity所在package
 
 
eureka:
  # 向註冊中心註冊自己
  client:
    register-with-eureka: true 
    
    # 從 Eureka Server 取已有註冊訊息(default true)，集群須為 true 才可使用附載均衡
    fetch-registry: true 
    service-url:
      defaultZone:  http://localhost:7001/eureka/
    
    