server:
  port: 7001

eureka:
  instance:    # hostname: localhost
    hostname: eureka7001.com # 多台Server 以改過host文件
  client:
    register-with-eureka: false # 不向註冊中心註冊自己
    fetch-registry: false # false 表自己是註冊中心，維護實例，不需要檢索服務
        service-url:    # 設置 Eureka Server 交互地址。查詢、註冊服務 到此地址, p.s url最後 eureka 不可改
    # defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
      
      # 相互守望找到另一台守望Server (3台以上 url ',' 隔開)
      defaultZone:  http://eureka7002.com:7002 